version: '3'

services:
  php:
    build: ./docker/php/fpm
    image: mikrotik_php
    container_name: mikrotik_php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.17.5-alpine
    container_name: mikrotik_nginx
    restart: always
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_PORT:-80}:80
    working_dir: /app
    depends_on:
      - php
